@startuml

class Professor {
    +String nome
    +String email
    +String id
    +String senha
    +Professor(String, String, String, String)
}

class Disciplina {
    +int cargahoraria
    +String nome
    +List<Alunos> alunos
    +Professor professor
    +Disciplina(String, int)
    +adicionarAluno(Aluno) : void
    +removerAluno(Aluno) : void
}

class Curriculo {
    +String nome
    +int creditosTotais
    +List<Disciplina> disciplinas
    +Curriculo(String, int)
    +adicionarDisciplina(Disciplina) : void
    +removerDisciplina(Disciplina) : void
}

class Curso {
    +String nome
    +int creditosTotais
    +List<Disciplina> disciplinas
    +Curso(String, int)
    +adicionarDisciplina(Disciplina) : void
    +removerDisciplina(Disciplina) : void
}

class Aluno {
    +String nome
    +String email
    +String matricula
    +List<Curso> cursosMatriculados
    +Aluno(String, String, String)
    +adicionarCurso(Curso) : void
    +removerCurso(Curso) : void
}

class Turma {
    +String nome
    +List<Disciplina> disciplinas
    +List<Aluno> alunos
    +Professor professor
    +Turma(String, Professor)
    +adicionarAluno(Aluno) : void
    +removerAluno(Aluno) : void
}

class Secretaria {
    +String nome
    +String email
    +String senha
    +Secretaria(String, String, String)
    +criarTurma(String, Professor) : void
    +criarAluno(String, String, String) : void
    +criarProfessor(String, String, String) : void
}

class DadosUniversidade {
    +List<Secretaria> secretarias
    +List<Professor> professores
    +List<Curso> cursos
    +List<Aluno> alunos
    +DadosUniversidade(Secretaria, Professor, Curso, Aluno)
    +adicionarSecretaria(Secretaria) : void
    +removerSecretaria(Secretaria) : void
}

class Main {
    +void main(String[])
    +void adicionarProfessor(Professor) : void
    +void adicionarAluno(Aluno) : void
    +void criarCurso(String, int) : void
    +void criarDisciplina(String, int) : void
    +void criarTurma(String, Professor) : void
    +void adicionarDisciplinaTurma(Disciplina) : void
}

class SistemaDeCobrancas {
    +void criarCobranca(Aluno, List<Disciplina>) : void
}

Professor "1" --> "*" Disciplina : professor
Disciplina "1" --> "*" Curriculo : disciplinas
Curriculo "1" --> "*" Curso : cursosMatriculados
Aluno "1" --> "*" Curso : cursosMatriculados
Curso "1" --> "*" Aluno : alunos
Turma "1" --> "*" Disciplina : disciplinas
Turma "1" --> "*" Aluno : alunos
DadosUniversidade "1" --> "*" Secretaria : secretarias
DadosUniversidade "1" --> "*" Professor : professores
DadosUniversidade "1" --> "*" Curso : cursos
DadosUniversidade "1" --> "*" Aluno : alunos
Main "1" --> "*" SistemaDeCobrancas : criarCobranca

@enduml
